- name: Install open-iscsi, NFSv4 client
  apt:
    state: present
    name:
      - open-iscsi
      - nfs-common
      - curl
      - util-linux
      - grep
      - jq

- name: Environment check script
  shell: |
    curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/scripts/environment_check.sh | bash
