- name: Install open-iscsi, NFSv4 client
  apt:
    state: present
    name:
      - open-iscsi
      - nfs-common
      - curl
      - util-linux
      - grep
      - jq

- name: Environment check script
  shell: |
    curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/scripts/environment_check.sh | bash
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: inventory_hostname in groups['master']

- name: Install longhorn
  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  community.kubernetes.k8s:
    state: present
    template:
      path: longhorn.yaml
  when: inventory_hostname in groups['master']
