---
roles:
  - name: githubixx.ansible_role_wireguard
    version: 7.9.0
  - name: xanmanning.k3s
    version: v2.5.3
  - name: geerlingguy.swap
    version: 1.0.2
collections:
  - name: kubernetes.core
    version: 1.1.1
