---
- become: yes
  hosts: k3s_cluster
  name: setup cluster node
  roles:
    - role: githubixx.ansible_role_wireguard
      tags: role-wireguard
    - role: xanmanning.k3s
      tags: k3s-setup
    - role: geerlingguy.swap
      tags: k3s-setup
  tasks:
    - name: download k3s cni plugins
      get_url:
        url: https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz
        dest: /var/local/cni.tgz
      tags: k3s-setup
      when: inventory_hostname in groups['master']
    - name: create opt/cni/bin directory
      ansible.builtin.file:
        state: directory
        mode: u=rwx,g=rx,o=rx
        path: /opt/cni/bin
      tags: k3s-setup
    - name: extract cni plugins
      unarchive:
        src: /var/local/cni.tgz
        remote_src: yes
        dest: /opt/cni/bin/
      tags: k3s-setup
      when: inventory_hostname in groups['master']
    - name: Enable ip forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: yes
        state: present
        reload: yes
      tags: k3s-setup
    - name: copy the calico yaml file
      template:
        src: calico.yaml
        dest: /var/local/calico.yaml
        mode: u=rw,g=r,o=r
      tags: k3s-setup
      when: inventory_hostname in groups['master']
    - name: install calico
      ansible.builtin.shell: kubectl apply -f "/var/local/calico.yaml"
      tags: k3s-setup
      when: inventory_hostname in groups['master']
      ignore_errors: true
    - name: Install Helm in master nodes
      ansible.builtin.shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      tags: k3s-setup
      when: inventory_hostname in groups['master']
      ignore_errors: true
    - name: Install traefik helm repository
      shell: helm repo add traefik https://helm.traefik.io/traefik
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s/yaml
      tags: k3s-setup
      when: inventory_hostname in groups['master']

    - name: Install traefik chart
      shell: helm install traefik traefik/traefik
      environment:
        # specify the location of the k3s created kubeconfig file
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      tags: k3s-setup
      when: inventory_hostname in groups['master']
      ignore_errors: true

    - name: make sure pip3 is installed
      apt: name=python3-pip state=present
      tags: [python, k3s-setup, flux]
      when: inventory_hostname in groups['master']

    - name: Install openshift python module
      pip:
        name: openshift==0.11.2
      tags: [python, k3s-setup, flux]
      when: inventory_hostname in groups['master']

    - name: create gitlab credentials secret
      shell: |
        kubectl create secret generic gitlab-http-credentials \
          --from-literal=username={{ gitlab_user }} \
          --from-literal=password={{ gitlab_token }}
      tags: [k3s-setup, flux]
      ignore_errors: true
      when: inventory_hostname in groups['master']

    - name: Install flux v2
      shell: curl -s https://toolkit.fluxcd.io/install.sh | sudo bash
      args:
        creates: /usr/local/bin/flux
      when: inventory_hostname in groups['master']
      tags: [k3s-setup]

    - name: Bootstrap flux
      shell: |
        flux bootstrap gitlab \
          --owner {{ gitlab_owner }} \
          --repository {{ gitlab_repo }} \
          --branch {{ gitlab_branch }} \
          --path {{ gitlab_path }} \
          --kubeconfig /etc/rancher/k3s/k3s.yaml
      environment:
        GITLAB_TOKEN: "{{ gitlab_token }}"
      ignore_errors: true
      when: inventory_hostname in groups['master']
      tags: k3s-setup

    - name: Add DO token as a k8s secret
      shell: |
        kubectl create secret generic do-token \
          --from-literal=do-token={{ do_token | string | b64encode }}
      tags: [k3s-setup, digitalocean, secrets]
      when: inventory_hostname in groups['master']
      ignore_errors: true
